blank_issues: false
contact_links:
  - name: Help and Documentation
    url: https://github.com/thejaustin/ShizukuPlus/wiki
    about: Please read the wiki before creating a bug report.
  - name: Telegram
    url: https://t.me/ShizukuPlus
    about: Join our community on Telegram for support and news.
